name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            README.md
            DEPLOYMENT.md
            profile/README.md
